#!/usr/bin/env python3
"""One-time build: fetch the Gregstrq CIAAW/AME isotope CSV and emit ../js/elements.js.

The deployed app ships only the generated elements.js (pure static data, no runtime
fetch). Re-run this only to refresh the dataset:

    python3 data/build_elements.py

Filter rule: keep isotopes with natural abundance > 0. This correctly includes
naturally-occurring long-lived radionuclides (Rb-87, Re-187, In-115, Th-232,
U-238, ...) that the CSV flags is_radioactive=true but which carry real natural
abundance and must contribute to the average atomic weight. Abundances are
normalised from percent -> fraction.
"""
import csv
import io
import sys
import urllib.request

URL = "https://raw.githubusercontent.com/Gregstrq/Isotope-data/master/isotopes_data.csv"
OUT = "js/elements.js"


def main():
    # Use a locally cached CSV if passed as argv[1] (network may be restricted),
    # otherwise fetch the live source.
    if len(sys.argv) > 1:
        with open(sys.argv[1], encoding="utf-8") as fh:
            raw = fh.read()
    else:
        raw = urllib.request.urlopen(URL, timeout=60).read().decode("utf-8")
    reader = csv.DictReader(io.StringIO(raw))

    elements = {}  # symbol -> {sym, z, name, isotopes:[{a,mass,abundance}]}
    for row in reader:
        try:
            z = int(row["atomic_number"])
        except (ValueError, TypeError):
            continue
        if z < 1:  # skip neutron (atomic_number 0) and junk
            continue
        abundance = float(row["abundance"] or 0)
        if abundance <= 0:
            continue  # not naturally occurring
        mass = float(row["mass [u]"])
        a = int(row["mass_number"])
        sym = row["symbol"]
        el = elements.setdefault(sym, {"sym": sym, "z": z, "name": row["name"], "isotopes": []})
        el["isotopes"].append({"a": a, "mass": mass, "abundance": abundance / 100.0})

    # normalise abundances per element so they sum to exactly 1.0 (guard against
    # rounding in the source), then sort isotopes by mass number.
    for el in elements.values():
        el["isotopes"].sort(key=lambda i: i["a"])
        total = sum(i["abundance"] for i in el["isotopes"])
        if total > 0:
            for i in el["isotopes"]:
                i["abundance"] = i["abundance"] / total

    ordered = sorted(elements.values(), key=lambda e: e["z"])

    lines = [
        "// Auto-generated by data/build_elements.py from CIAAW/AME isotope data.",
        f"// Source: {URL}",
        "// Includes only naturally-occurring isotopes (abundance > 0).",
        "// Abundances are normalised mass fractions (sum to 1 per element).",
        "// Monoisotopic mass in this app uses the LIGHTEST isotope of each element.",
        "export const ELEMENTS = {",
    ]
    for el in ordered:
        parts = [
            "{a:%d,mass:%.9f,abundance:%.10g}" % (i["a"], i["mass"], i["abundance"])
            for i in el["isotopes"]
        ]
        lines.append(
            "  %s: {z:%d,name:%r,isotopes:[%s]},"
            % (el["sym"], el["z"], el["name"], ",".join(parts))
        )
    lines.append("};")

    text = "\n".join(lines) + "\n"
    with open(OUT, "w", newline="\n") as f:
        f.write(text)
    print(f"Wrote {OUT}: {len(ordered)} elements.")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:  # noqa: BLE001
        print(f"build failed: {exc}", file=sys.stderr)
        sys.exit(1)
